
#pragma once

#define COMBO_TERM 18
#define RGBLIGHT_LIMIT_VAL 50
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 50
#define HOLD_ON_OTHER_KEY_PRESS
#define FORCE_NKRO
#define SPLIT_TRANSPORT_MIRROR
#define RGB_MATRIX_KEYPRESSES // optional, only if you want reactive keys
#undef ENABLE_RGB_MATRIX_SOLID_COLOR
#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define MIDI_ADVANCED
#define DYNAMIC_KEYMAP_LAYER_COUNT 6
